apiVersion: v1
kind: Service
metadata:
  name: commandnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports: 
    - name : commandnpservice
      protocol: TCP
      port: 80
      targetPort: 80